//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_Final.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2017_Final.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 240 180 10
        ///1 100 29907
        ///120 90
        ///------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///------------------------------------------------------------------------------------------------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string charleston_road {
            get {
                return ResourceManager.GetString("charleston_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 872 975 5
        ///5 100 2654677
        ///436 487
        ///------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lets_go_higher {
            get {
                return ResourceManager.GetString("lets_go_higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 667 540 7
        ///1 100 94860
        ///333 270
        ///-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string opera {
            get {
                return ResourceManager.GetString("opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 559 404 10
        ///1 100 21634
        ///279 202
        ///--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///---------------------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rue_de_londres {
            get {
                return ResourceManager.GetString("rue_de_londres", resourceCulture);
            }
        }
    }
}
