//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_problem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pizza_problem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 1000 6 14
        ///TMMMTTTMMMMTMMTTMTTMTTMMTMMMTTTTTTMTTTTTTMMMMMMMTMMMMTTTMTMMTTTTTTMMMMMTTMTMTMMMTMTTMMTTMMMTTMMMTTTTMTTTMTMMMTTMTMTTMTTMTTTTMMMTTTMMTTMMMTTMMTMTMMTTMMTTMTMMMTMMMTMTTMMTMMTTMTTMMMMMTTTMMMTMMMMMMTMTTMTTTTTMMMMMMTMTMMTTTTMMTTTTMTTTMTMMTTMMTMTTMTTTMTMMTMMTMMTTMMMTTTMMTTTTTMTMTTMMMTMTTMTMMTTMMMMTTMTTMMMTTTTTMMMTTTTMMMTTMTMTTTTTMTMTTTTMTMTTMTMMTMMMMTTMTMTTTMTMTMMMTMTTMTMTMTTTTTMMTMMTTMMMMMMMTTTTMTMMMTTMMMMTTMMTTMTTTMMMMMTMMTMTMMTMTTMMMTTMMTMTTTTTTTTTTTTTMMMTTTTMMMMMTMMTTMMTMMMTTTTTMMMTTTMTTTMMMMMT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string big {
            get {
                return ResourceManager.GetString("big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 5 1 6
        ///TTTTT
        ///TMMMT
        ///TTTTT
        ///.
        /// </summary>
        public static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 250 4 12
        ///TMMMTTTMMMMTMMTTMTTMTTMMTMMMTTTTTTMTTTTTTMMMMMMMTMMMMTTTMTMMTTTTTTMMMMMTTMTMTMMMTMTTMMTTMMMTTMMMTTTTMTTTMTMMMTTMTMTTMTTMTTTTMMMTTTMMTTMMMTTMMTMTMMTTMMTTMTMMMTMMMTMTTMMTMMTTMTTMMMMMTTTMMMTMMMMMMTMTTMTTTTTMMMMMMTMTMMTTTTMMTTTTMTTTMTMMTTMMTMTTMTTTMTMMTM
        ///MTMMTTMMMTTTMMTTTTTMTMTTMMMTMTTMTMMTTMMMMTTMTTMMMTTTTTMMMTTTTMMMTTMTMTTTTTMTMTTTTMTMTTMTMMTMMMMTTMTMTTTMTMTMMMTMTTMTMTMTTTTTMMTMMTTMMMMMMMTTTTMTMMMTTMMMMTTMMTTMTTTMMMMMTMMTMTMMTMTTMMMTTMMTMTTTTTTTTTTTTTMMMTTTTMMMMMTMMTTMMTMMMTTTTTMMMTTTMTTTMMMMMT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 7 1 5
        ///TMMMTTT
        ///MMMMTMM
        ///TTMTTMT
        ///TMMTMMM
        ///TTTTTTM
        ///TTTTTTM
        ///.
        /// </summary>
        public static string small {
            get {
                return ResourceManager.GetString("small", resourceCulture);
            }
        }
    }
}
