//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2018_Final.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2018_Final.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 7 2 3
        ///R 3 2 25
        ///.#
        ///##
        ///.#
        ///U 1 4 1
        ///####
        ///U 2 2 5
        ///##
        ///##.
        /// </summary>
        internal static string a_example {
            get {
                return ResourceManager.GetString("a_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 1000 1 200
        ///R 1 2 1
        ///##
        ///R 4 3 3
        ///##.
        ///##.
        ///###
        ///##.
        ///R 2 3 2
        ///###
        ///.##
        ///R 3 4 4
        ///.#..
        ///####
        ///.###
        ///R 4 6 1
        ///.##...
        ///######
        ///.####.
        ///..##..
        ///R 2 2 2
        ///##
        ///##
        ///R 3 5 8
        ///.##..
        ///#####
        ///.##..
        ///R 6 4 6
        ///#...
        ///###.
        ///###.
        ///###.
        ///####
        ///##..
        ///R 1 2 1
        ///##
        ///R 1 1 1
        ///#
        ///R 3 5 3
        ///###..
        ///..###
        ///..###
        ///R 3 3 1
        ///###
        ///.##
        ///.##
        ///R 4 3 6
        ///#..
        ///##.
        ///###
        ///#.#
        ///R 3 4 7
        ///###.
        ///.###
        ///..##
        ///R 8 6 29
        ///..#...
        ///######
        ///######
        ///#####.
        ///#####.
        ///####..
        ///.####.
        ///...#..
        ///R 3 4 1
        ///.##.
        ///####
        ///.##.
        ///R 7 5 10
        ///#....
        ///####.
        ///.####
        ///...#.
        ///..##.
        ///.##..
        ///##...
        ///R 5 5 11
        ///###..
        ///####.
        ///..#..
        ///#####
        ///..##.
        ///R 1 2 1
        ///##
        ///R 3 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string b_short_walk {
            get {
                return ResourceManager.GetString("b_short_walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 1000 20 200
        ///R 1 11 6
        ///###########
        ///R 11 13 68
        ///#############
        ///#############
        ///#############
        ///#############
        ///#############
        ///#############
        ///#############
        ///#############
        ///#############
        ///#############
        ///#############
        ///R 11 3 14
        ///###
        ///###
        ///###
        ///###
        ///###
        ///###
        ///###
        ///###
        ///###
        ///###
        ///###
        ///R 1 5 4
        ///#####
        ///R 9 18 110
        ///##################
        ///##################
        ///##################
        ///##################
        ///##################
        ///##################
        ///##################
        ///##################
        ///##################
        ///R 10 11 69
        ///###########
        ///###########
        ///###########
        ///###########
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string c_going_green {
            get {
                return ResourceManager.GetString("c_going_green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 1000 5 200
        ///R 2 3 3
        ///###
        ///..#
        ///R 2 2 3
        ///##
        ///##
        ///R 3 2 1
        ///##
        ///#.
        ///#.
        ///R 3 2 3
        ///.#
        ///.#
        ///##
        ///R 3 2 1
        ///.#
        ///##
        ///#.
        ///R 2 3 3
        ///###
        ///..#
        ///R 3 2 4
        ///#.
        ///##
        ///.#
        ///R 2 2 4
        ///##
        ///##
        ///R 3 2 4
        ///.#
        ///##
        ///.#
        ///R 2 3 1
        ///###
        ///#..
        ///R 2 3 1
        ///###
        ///..#
        ///R 2 3 3
        ///###
        ///#..
        ///R 2 3 4
        ///#..
        ///###
        ///R 4 1 3
        ///#
        ///#
        ///#
        ///#
        ///R 2 3 3
        ///##.
        ///.##
        ///R 2 3 1
        ///.##
        ///##.
        ///R 2 3 2
        ///.##
        ///##.
        ///R 2 3 1
        ///###
        ///#..
        ///R 3 2 3
        ///##
        ///#.
        ///#.
        ///R 2 3 3
        ///..#
        ///###
        ///R 3 2 1
        ///#.
        ///##
        ///#.
        ///R 2 3 2
        ///###
        ///#..
        ///R 2 3 1
        ///###
        ///#..
        ///R 3 2 4
        ///#.
        ///#.
        ///##
        ///R 3 2 1
        ///##
        ///#.
        ///#.
        ///R 2 3 1
        ///.##
        ///##.
        ///R 3 2 2
        ///#.
        ///##
        ///.#
        ///R 2 3 3
        ///..#
        ///###
        ///R 3 2 4
        ///##
        ///#.
        ///#.
        ///R 3 2 2
        ///.#
        ///##
        ///.#
        ///R 2 3 4
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d_wide_selection {
            get {
                return ResourceManager.GetString("d_wide_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 1000 20 20
        ///R 2 3 25
        ///###
        ///##.
        ///R 1 1 5
        ///#
        ///R 7 8 125
        ///#.......
        ///###.....
        ///####....
        ///.####...
        ///.#######
        ///...#####
        ///.....#..
        ///R 4 7 100
        ///..####.
        ///.#####.
        ///#######
        ///...####
        ///R 4 6 95
        ///###...
        ///#####.
        ///######
        ///#####.
        ///R 5 5 75
        ///..#..
        ///.###.
        ///#####
        ///####.
        ///.##..
        ///R 8 5 120
        ///#....
        ///###..
        ///##...
        ///##...
        ///###..
        ///####.
        ///####.
        ///#####
        ///R 9 4 140
        ///##..
        ///###.
        ///####
        ///.###
        ///.###
        ///.###
        ///.###
        ///####
        ///.###
        ///R 3 4 35
        ///##..
        ///.###
        ///..##
        ///R 7 5 115
        ///.##..
        ///####.
        ///####.
        ///.###.
        ///.###.
        ///.####
        ///.###.
        ///R 4 8 90
        ///#####...
        ///.#######
        ///..#####.
        ///...#....
        ///R 7 8 135
        ///#.......
        ///###.....
        ///#####.##
        ///####### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string e_precise_fit {
            get {
                return ResourceManager.GetString("e_precise_fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 1000 10 180
        ///R 1 3 1
        ///###
        ///R 3 4 10
        ///####
        ///####
        ///####
        ///R 3 1 5
        ///#
        ///#
        ///#
        ///R 1 2 4
        ///##
        ///R 3 5 12
        ///#####
        ///#####
        ///#####
        ///R 3 3 14
        ///###
        ///###
        ///###
        ///R 4 4 5
        ///####
        ///####
        ///####
        ///####
        ///R 1 1 2
        ///#
        ///R 3 2 7
        ///##
        ///##
        ///##
        ///R 2 3 1
        ///###
        ///###
        ///R 3 5 1
        ///#####
        ///#####
        ///#####
        ///R 2 3 1
        ///###
        ///###
        ///R 1 3 2
        ///###
        ///R 2 2 1
        ///##
        ///##
        ///R 5 4 29
        ///####
        ///####
        ///####
        ///####
        ///####
        ///R 2 3 12
        ///###
        ///###
        ///R 1 2 4
        ///##
        ///R 1 1 1
        ///#
        ///R 3 4 16
        ///####
        ///####
        ///####
        ///R 2 2 1
        ///##
        ///##
        ///R 5 1 8
        ///#
        ///#
        ///#
        ///#
        ///#
        ///R 4 4 14
        ///####
        ///####
        ///####
        ///####
        ///R 4 4 9
        ///####
        ///####
        ///####
        ///####
        ///R 5 2 9
        ///##
        ///##
        ///##
        ///##
        ///##
        ///R 4 2 1
        ///##
        ///##
        ///##
        ///##
        ///R 3 2 5
        ///##
        ///##
        ///##
        ///R  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string f_different_footprints {
            get {
                return ResourceManager.GetString("f_different_footprints", resourceCulture);
            }
        }
    }
}
