//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2015_Qual_WithLiron.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2015_Qual_WithLiron.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 5 1 2 5
        ///0 0
        ///3 10
        ///3 10
        ///2 5
        ///1 5
        ///1 1        ///.
        /// </summary>
        internal static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 100 80 45 625
        ///10 23
        ///0 40
        ///4 40
        ///3 57
        ///11 78
        ///10 82
        ///14 27
        ///1 39
        ///6 75
        ///0 47
        ///3 49
        ///8 8
        ///0 42
        ///3 18
        ///10 39
        ///8 71
        ///3 52
        ///9 42
        ///12 95
        ///0 10
        ///12 89
        ///11 17
        ///5 44
        ///2 48
        ///15 31
        ///5 38
        ///1 48
        ///1 54
        ///13 55
        ///9 65
        ///12 91
        ///11 67
        ///8 57
        ///15 56
        ///6 5
        ///8 83
        ///13 27
        ///9 89
        ///13 78
        ///9 23
        ///11 27
        ///0 73
        ///3 64
        ///4 63
        ///1 27
        ///3 72
        ///1 61
        ///4 44
        ///10 17
        ///5 83
        ///5 92
        ///3 35
        ///4 27
        ///14 98
        ///10 36
        ///9 74
        ///2 73
        ///11 66
        ///2 61
        ///6 7
        ///15 83
        ///8 91
        ///10 95
        ///13 48
        ///12 41
        ///3 66
        ///0 51
        ///5 4
        ///4 28
        ///3 37
        ///15 8
        ///14 2
        ///5 3
        ///10 48
        ///6 33
        ///14 63
        ///7 34
        ///4 23
        ///3 94
        ///8 98
        ///2 28
        ///5 55
        ///2 40
        ///3 18
        ///1 6
        ///4 68
        ///3 18
        ///2 40
        ///3 60
        ///5 25
        ///4 60
        ///3 27
        ///4 24
        ///3 36
        ///5 95
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
